name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          cache-dependency-path: portfolio/package-lock.json
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: cd portfolio && npm install
      - name: Build with Next.js
        run: cd portfolio && npm run build
      - name: Find build output
        run: |
          echo "Current directory:"
          pwd
          echo "Files in portfolio directory:"
          ls -la portfolio/
          echo "Looking for .next directory:"
          ls -la portfolio/.next || echo "No .next directory found"
          echo "Looking for out directory:"
          ls -la portfolio/out || echo "No out directory found"
          echo "All build outputs:"
          find portfolio -type d -name "out" -o -name ".next" -o -name "dist"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Make sure this is v3, not v4
        with:
          path: ./portfolio/out  # Make sure this points to the output directory

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
